# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42a72d2ea73749222a9e7fc803b2ddfa5577d708396cef3c1dc2d799bcd2282722af122ef9e8f939f55d411e04ff9878e772dfb6342940f7149f1612bb839346

test:
  secret_key_base: 28e52900792baafc04e1920b4b418b72163e78d434e17fcf35826415cc6c6a224afb69182223748a491d9a51e85f3f30a7fbe8197371833d01a0959cedc025e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
